# Workflow name
name: 'Web Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  deploy:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: npm i
      - run: git config --global user.email "vinitkothawade98@gmail.com"
      - run: git config --global user.name "Vinit"
      - run: npm run deploy