name: 'Storybook Deployment'

on: 
  push:
    branches: 
      - main 

jobs:
  deployStorybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm i
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.REPO_TOKEN }}